title: "<p align='center'> Bipul Kumar Singh </p>"
logo: /assets/img/portfolio_pic.jpg

description: |
  <p align="center">
  <a href="docs/Bipul_Kumar_product_manager.pdf" target="_blank">Resume</a> |
  <a href="experience.html" target="_blank">Experience</a> |
  <a href="certifications.html" target="_blank">Certifications</a> |
  <a href="education.html" target="_blank">Education</a> |
  <a href="Patent.html" target="_blank">Patent</a> |
  <a href="https://www.linkedin.com/in/vipul-singh09/" target="_blank">LinkedIn</a> |
  <a href="https://github.com/bipulkumar1" target="_blank">GitHub</a> |
  </p>
  <br>   
  Tech Savvy | Passionate for AI-ML-DEEP Learning and EDGE-AI |
  Specialist in Embedded - IoT & Automotive
  </br>

theme: jekyll-theme-minimal
show_downloads: false
